#!/usr/bin/env bash

if [ "$(uname)" != "Darwin" ]; then
  echo "Skipping Projects scaffolding on non-MacOS platform"
  exit 0
fi

mkdir -p ~/projects/forks
mkdir -p ~/projects/playground
mkdir -p ~/projects/repos
